baseURL = "https://Prammerus.github.io/blog/"
languageCode = "de-at"
title = "Ääs Thut"
theme = "hugo-coder"

[pagination]
    pagerSize = 20

[params]
    author = "Ääs Thut"
    description = "Gedanken aus dem Zettelkasten."
    footerContent = "Primat des Vollzugs."
    hideFooter = false
    colorProtocol = "auto"
    customCSS = ["css/custom.css"]
